### ISSUE TITLE
Seems there is redundant print

### ISSUE THREAD

**Issue by kiddick** [panyanyany/beeprint#19]
https://github.com/panyanyany/beeprint/blob/06a0600a9a9c2e2cea98f669b2734b7f47c2fc92/beeprint/terminal_size.py#L33

Is it here for debug reason?

```
    if tuple_xy is None:
        print("default")
        tuple_xy = (80, 25)      # default value
return tuple_xy
```

**Comment by panyanyany** [comment]
sorry, It's a mistake. 
The function is copied from others and my tests didn't found that output.

**Comment by panyanyany** [comment]
by the way, how could you trigger this print ?

**Comment by panyanyany** [comment]
New release is available. Thank you for your supports. ;-)
