### ISSUE TITLE
Doesn't work with bpython

### ISSUE THREAD

**Issue by jiujitsu** [panyanyany/beeprint#8]
Tested on bpython version `0.15` and python version `2.7.10`. It does work with ipython, although the output is a little awkward, but that is another issue.

```python
>>> from beeprint import pp
>>> pp({'foo': 'bar'})
>>>
```

**Comment by panyanyany** [comment]
actually i had the same problem when it comes to `bpython version 0.15 on top of Python 2.7.11+`. 
not only pp didn't work, but also bulitin print.

but it works find on `bpython version 0.15 on top of Python 3.5.1+`

**Comment by jiujitsu** [comment]
Ah ok! I'll let you decide if we should close this ticket or not then. Thanks!
